/*
 * Zuper - Shoutcast and Icecast Radio Player With History - v2.1.1
 * Copyright 2017-2019, LambertGroup
 *
 */

 (function(d){function Q(a,b,c,e){d(a.thumbsHolder_Thumbs[a.current_img_no]).css({background:b.playlistRecordBgOnColor,"border-bottom-color":b.playlistRecordBottomBorderOnColor,color:b.playlistRecordTextOnColor});if(""!=b.radio_stream)var p=b.radio_stream;return p}function V(a,b,c,e){var p=b.noImageAvailable,l="",y="";if(""!=a&&void 0!=a){l=a.match(/\.([^\./\?#]+)($|\?|#)/)[1];if("jpg"==l||"jpeg"==l||"JPG"==l||"JPEG"==l)y="&iiurlparam=qlow-1000px";d.get("https://commons.wikimedia.org/w/api.php?action=query&titles=Image:"+
 a+"&prop=imageinfo&format=xml&origin=*&iiprop=url"+y,{},function(a){""!=d("ii",a).attr("thumburl")&&void 0!=d("ii",a).attr("thumburl")?(p=d("ii",a).attr("thumburl"),c.wiki_photo_path=p):""!=d("ii",a).attr("url")&&void 0!=d("ii",a).attr("url")&&(p=d("ii",a).attr("url"),c.wiki_photo_path=p);W(b,c,e,p)})}}function X(a,b,c,e,p,l,y,n,t,w,g,z,x,q,r,A,B,k,v){var F=c.noImageAvailable,h="",u="";if(""!=a&&void 0!=a){h=a.match(/\.([^\./\?#]+)($|\?|#)/)[1];if("jpg"==h||"jpeg"==h||"JPG"==h||"JPEGs"==h)u="&iiurlparam=qlow-200px";
 d.get("https://commons.wikimedia.org/w/api.php?action=query&titles=Image:"+a+"&prop=imageinfo&format=xml&origin=*&iiprop=url"+u,{},function(a){""!=d("ii",a).attr("thumburl")&&void 0!=d("ii",a).attr("thumburl")?F=d("ii",a).attr("thumburl"):""!=d("ii",a).attr("url")&&void 0!=d("ii",a).attr("url")&&(F=d("ii",a).attr("url"));b.playlist_images_arr[v]=F})}0!==(v+1)%3&&v!=b.playlist_arr.length-1||setTimeout(function(){R(b,c,e,p,l,y,n,t,w,g,z,x,q,r,A,B,k)},1E3)}function P(a){a=a.split("");a.forEach(function(b,
 c){var d="\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00df\u00d2\u00d3\u00d4\u00d5\u00d5\u00d6\u00d8\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u00f0\u00c7\u00e7\u00d0\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u00d1\u00f1\u0160\u0161\u0178\u00ff\u00fd\u017d\u017e\u2019".indexOf(b);-1!=d&&(a[c]="AAAAAAaaaaaaBOOOOOOOooooooEEEEeeeeeCcDIIIIiiiiUUUUuuuuNnSsYyyZz'"[d])});return a.join("").trim()}
 function M(a,b){var c=new XMLHttpRequest;c.open(a.method,"https://zet.pluginsandthemes.ro/"+a.url);c.onload=c.onerror=function(){b(a.method+" "+a.url+"\n"+c.status+" "+c.statusText+"\n\n"+(c.responseText||""))};/^POST/i.test(a.method)&&c.setRequestHeader("Content-Type","application/x-www-form-urlencoded");c.send(a.data)}function Y(a,b,c,d,p,l,y,n,t,w,g,z,x,q,r,A,B){""!=a.curTitle&&a.isHistoryGenerated&&a.prevTitle!=a.curTitle&&(""!=a.prevTitle&&(30<=a.gen_total_images&&(a.gen_total_images--,a.playlist_arr.pop(),
 a.playlist_images_arr.pop()),a.gen_total_images++,a.playlist_arr.unshift(a.prevTitle),a.playlist_images_arr.unshift(a.prev_song_image),R(a,b,c,d,p,l,y,n,t,w,g,z,x,q,r,A,B)),a.prevTitle=a.curTitle)}function H(a,b,c,d,p,l,y,n,t,w,g,z,x,q,r,A,B,k){if(b.showOnlyPlayButton||a.isRadioCo)a.isRadioCo&&M({method:"GET",url:"http://public.radio.co/stations/"+a.mount_point+"/status?my_rand="+Math.random()},function(e){startPoint=e.indexOf("{");-1!==startPoint&&(lengthPoint=e.length,e=e.substr(startPoint,lengthPoint),
 e=JSON.parse(e),a.curTitle=e.current_track.title,K(a,b,c,l,y,n,t,w,g,z,x),Y(a,b,l,c,d,p,r,y,n,t,w,g,z,x,q,A,B))});else{!1===a.now_playing_found&&a.now_playing_current_k<a.now_playing_arr_lenght&&a.now_playing_current_k++;var e=a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.now_playing_arr[a.now_playing_current_k]+("7.html"!=a.now_playing_arr[a.now_playing_current_k]?"?my_rand="+Math.random():"");0===a.now_playing_current_k&&(e=a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.now_playing_arr[a.now_playing_current_k]+
 ("7.html"!=a.now_playing_arr[a.now_playing_current_k]?"&my_rand="+Math.random():""));""!=a.ip&&a.now_playing_current_k<a.now_playing_arr_lenght?(M({method:"GET",url:e},function(e){var h="";switch(a.now_playing_current_k){case 0:if(-1!=e.indexOf("<SONGTITLE>")){a.now_playing_found=!0;var u=e.indexOf("<SONGTITLE>")+11;var m=e.indexOf("</SONGTITLE>")-u;h=e.substr(u,m);a.curTitle=h;K(a,b,c,l,y,n,t,w,g,z,x,q,k)}else H(a,b,c,d,p,l,y,n,t,w,g,z,x,q,r,A,B,k);break;case 1:u=e.indexOf("<body>")+6;m=e.length;
 e=e.substr(u,m);e=e.replace("</body></html>","");h=e.split(",");""!=h[6]&&void 0!=h[6]&&"oracle:0"!=h[6]?(a.now_playing_found=!0,h=h[6],a.curTitle=h,K(a,b,c,l,y,n,t,w,g,z,x,q,k)):H(a,b,c,d,p,l,y,n,t,w,g,z,x,q,r,A,B,k);break;case 2:u=e.indexOf('{"icestats":');if(-1!==u){m=e.length;e=e.substr(u,m);e=JSON.parse(e);u=!1;for(var v=0;v<Object.keys(e.icestats.source).length&&!u;)m=e.icestats.source[v].listenurl,0<m.indexOf(a.mount_point)&&(u=!0,v--),v++;u&&""!=e.icestats.source[v].title&&void 0!=e.icestats.source[v].title&&
 (a.now_playing_found=!0,h=e.icestats.source[v].title,a.curTitle=h,K(a,b,c,l,y,n,t,w,g,z,x,q,k))}""==h&&(a.now_playing_found=!1,H(a,b,c,d,p,l,y,n,t,w,g,z,x,q,r,A,B,k));break;case 3:""!=a.mount_point&&(u=e.indexOf(a.mount_point));0<u&&(m=e.length,e=e.substr(u,m));m=e.indexOf("Currently playing:");-1==m&&(m=e.indexOf("Current Song:"));0<m&&(a.now_playing_found=!0,u=e.indexOf('<td class="streamstats">',m),u=0<u?u+24:e.indexOf('<td class="streamdata">',m)+23,m=e.indexOf("</td>",u),h=e.substr(u,m-u),a.curTitle=
 h,K(a,b,c,l,y,n,t,w,g,z,x,q,k));""==h&&(a.now_playing_found=!1,H(a,b,c,d,p,l,y,n,t,w,g,z,x,q,r,A,B,k));break;default:a.now_playing_found=!0,a.curTitle="Not available...",K(a,b,c,l,y,n,t,w,g,z,x,q,k)}}),""!=a.curTitle&&a.isHistoryGenerated&&a.prevTitle!=a.curTitle&&(""!=a.prevTitle&&(30<=a.gen_total_images&&(a.gen_total_images--,a.playlist_arr.pop(),a.playlist_images_arr.pop()),a.gen_total_images++,a.playlist_arr.unshift(a.prevTitle),a.playlist_images_arr.unshift(a.prev_song_image),R(a,b,l,c,d,p,r,
 y,n,t,w,g,z,x,q,A,B)),a.prevTitle=a.curTitle),Y(a,b,l,c,d,p,r,y,n,t,w,g,z,x,q,A,B)):(curSong="Data not available...",a.curTitle=curSong,K(a,b,c,l,y,n,t,w,g,z,x,q,k))}}function Z(a,b,c,e,p,l,y,n,t,w,g,z,x,q,r,A,B,k){b.grabLastFmPhoto&&(a.musicbrainzHistory_setTimeout_arr[k]=setTimeout(function(){var v=a.playlist_arr[k].split("-");v[0]=v[0].trim();a.the_artist_id_history_arr[k]="";a.the_wikidata_id_history_arr[k]="";photo_path=b.noImageAvailable;a.wiki_photo_path=photo_path;clearTimeout(a.musicbrainzHistory_setTimeout_arr[k]);
 v[0]=v[0].trim();d.get("https://musicbrainz.org/ws/2/artist/?query=artist:"+v[0],{},function(F){var h="",u,m="";a.the_artist_id_history_arr[k]="";var C=v[0];C=C.toLowerCase();C=P(C);d("artist",F).each(function(){u=d("name",this)[0];0<d("name",this).length&&""==a.the_artist_id_history_arr[k]&&(h=d(u).text(),h=h.toLowerCase(),h=P(h),C.toLowerCase()==h.toLowerCase()&&(a.the_artist_id_history_arr[k]=d(this).attr("id")))});""==a.the_artist_id_history_arr[k]&&"ROCK RADIO"!=v[0]&&(a.the_artist_id_history_arr[k]=
 d(d("artist",F)[0]).attr("id"));""!=a.the_artist_id_history_arr[k]&&void 0!=a.the_artist_id_history_arr[k]&&(a.musicbrainzHistory_setTimeout_arr[k]=setTimeout(function(){a.the_wikidata_id_history_arr[k]="";d.get("https://musicbrainz.org/ws/2/artist/"+a.the_artist_id_history_arr[k]+"?inc=url-rels",{},function(h){d("relation",h).each(function(){"image"==d(this).attr("type")&&0<d("target",this).length&&(m=d("target",this).text(),m=m.substr(m.indexOf("File:",10)+5,m.length),X(m,a,b,e,c,q,x,r,p,l,y,n,
 t,w,g,z,A,B,k));"wikidata"==d(this).attr("type")&&0<d("target",this).length&&""==m&&(a.the_wikidata_id_history_arr[k]=d("target",this).text(),a.the_wikidata_id_history_arr[k]=a.the_wikidata_id_history_arr[k].substr(a.the_wikidata_id_history_arr[k].indexOf("/Q",10)+1,a.the_wikidata_id_history_arr[k].length),d.get("https://www.wikidata.org/w/api.php?action=wbgetclaims&entity="+a.the_wikidata_id_history_arr[k]+"&property=P18&format=xml&origin=*",{},function(f){m=d("datavalue",d("mainsnak",f)).attr("value");
 X(m,a,b,e,c,q,x,r,p,l,y,n,t,w,g,z,A,B,k)}))});if(""==m||void 0==m)a.playlist_images_arr[k]=photo_path})},3E3*(k+1)))})},3E3*(k+1)))}function da(a,b,c,e,d,l,y,n,t,w,g,z,x,q,r,A,B,k,v){clearInterval(a.radioReaderAjaxInterval);if(-1!==b.radio_stream.indexOf("radio.co")){a.isRadioCo=!0;var p=b.radio_stream.match(a.myregexp_radioco);null!=p&&(a.http_or_https=p[1],a.ip=p[2],a.mount_point=p[3],a.port="")}else-1==b.radio_stream.indexOf("/",9)&&(b.radio_stream+="/;"),"/"==b.radio_stream.charAt(b.radio_stream.length-
 1)&&(b.radio_stream+=";"),p=b.radio_stream.match(a.myregexp),null!=p&&(a.http_or_https=p[1],a.ip=p[2],a.port=p[3],a.mount_point=p[4],";"==a.mount_point.trim()&&(a.mount_point=""));g.css({width:b.playerWidth+"px",height:b.imageHeight+"px",background:"url("+b.noImageAvailable+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"});if(!b.showOnlyPlayButton){H(a,b,c,q,x,e,d,l,y,n,t,w,g,z,r,A,B,v);a.radioReaderAjaxInterval=setInterval(function(){H(a,b,
 c,q,x,e,d,l,y,n,t,w,g,z,r,A,B,v)},1E3*b.nowPlayingInterval);a.playlist_arr=[];a.playlist_images_arr=[];var h=-1,u,m,C,D=0;a.isRadioCo?M({method:"GET",url:"http://public.radio.co/stations/"+a.mount_point+"/status?my_rand="+Math.random()},function(f){u=f.indexOf('"history":[{');if(-1!==u){m=f.length;f=f.substr(u+10,m);u=0;m=f.indexOf("}],");f=f.substr(u,m+2);var p=JSON.parse(f)}for(D=0;D<Object.keys(p).length;D++)""!=p[D].title&&"Empty Title"!=p[D].title&&0!=D&&(h++,a.playlist_arr[h]=p[D].title,a.playlist_images_arr[h]=
 b.noImageAvailable,Z(a,b,c,e,d,l,y,n,t,w,g,z,x,q,r,A,B,h));a.playlist_arr.length?R(a,b,e,c,q,x,r,d,l,y,n,t,w,g,z,A,B):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&k.click()}):M({method:"GET",url:a.http_or_https+"://"+a.ip+":"+a.port+"/"+a.history_arr[a.history_current_k]+"?my_rand="+Math.random()},function(f){if(-1!=f.indexOf("Current Song"))for(u=f.indexOf("Current Song")+12,m=f.length,f=f.substr(u,m),C=f.split("</td><td>"),C.shift(),D=0;D<C.length;D++)u=C[D].indexOf("</"),-1!=u&&(m=u,C[D]=
 C[D].substr(0,m),C[D]=C[D].replace(/<\/?[^>]+(>|$)/g,""),""!=C[D]&&"Empty Title"!=C[D]&&(h++,a.playlist_arr[h]=C[D],a.playlist_images_arr[h]=b.noImageAvailable,Z(a,b,c,e,d,l,y,n,t,w,g,z,x,q,r,A,B,h)));a.playlist_arr.length?R(a,b,e,c,q,x,r,d,l,y,n,t,w,g,z,A,B):a.isHistoryGenerated=!0;b.sticky&&b.startMinified&&k.click()})}a.isFlashNeeded?""!=a.myFlashObject&&a.myFlashObject.myAS3function(Q(a,b,c,e),b.initialVolume):(document.getElementById(a.audioID).src=Q(a,b,c,e),document.getElementById(a.audioID).load(),
 b.autoPlay&&d.click())}function W(a,b,c,e){c.css({background:"url("+e+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"});b.prev_song_image=b.cur_song_image;b.cur_song_image=e}function K(a,b,c,e,p,l,y,n,t,w,g,z,x){a.curSongText="";b.showTitle&&null!=a.curTitle&&""!=a.curTitle&&(a.curSongText+=a.curTitle);b.showRadioStation&&null!=b.radio_name&&""!=b.radio_name&&t.html(b.radio_name);var q=a.curTitle.split("-"),r=b.noImageAvailable;q[0]=q[0].trim();
 3<=q.length&&(q[0]=q[0].trim()+"-"+q[1].trim());if(b.grabLastFmPhoto&&""!=q[0].trim()){var A,B="",k,v="";a.the_artist_id="";a.the_wikidata_id="";r=b.noImageAvailable;a.wiki_photo_path=r;clearTimeout(a.musicbrainz_setTimeout);clearTimeout(a.no_artist_image_setTimeout);q[0]=q[0].trim();""!=q[0]&&void 0!=q[0]&&a.prevTitle!=a.curTitle&&(g.css({background:"url("+r+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover"}),a.musicbrainz_setTimeout=setTimeout(function(){d.get("https://musicbrainz.org/ws/2/artist/?query=artist:"+
 q[0],{},function(c){a.the_artist_id="";A=q[0];A=A.toLowerCase();A=P(A);d("artist",c).each(function(){k=d("name",this)[0];0<d("name",this).length&&""==a.the_artist_id&&(B=d(k).text(),B=B.toLowerCase(),B=P(B),A.toLowerCase()==B.toLowerCase()&&(a.the_artist_id=d(this).attr("id")))});""==a.the_artist_id&&"ROCK RADIO"!=q[0]&&(a.the_artist_id=d(d("artist",c)[0]).attr("id"));""!=a.the_artist_id&&void 0!=a.the_artist_id&&(a.musicbrainz_setTimeout=setTimeout(function(){a.the_wikidata_id="";d.get("https://musicbrainz.org/ws/2/artist/"+
 a.the_artist_id+"?inc=url-rels",{},function(c){d("relation",c).each(function(){"image"==d(this).attr("type")&&0<d("target",this).length&&(v=d("target",this).text(),v=v.substr(v.indexOf("File:",10)+5,v.length),V(v,b,a,g));"wikidata"==d(this).attr("type")&&0<d("target",this).length&&(a.the_wikidata_id=d("target",this).text(),a.the_wikidata_id=a.the_wikidata_id.substr(a.the_wikidata_id.indexOf("/Q",10)+1,a.the_wikidata_id.length),b.showBioBut&&(d(".historyTitle_bio",e).html(q[0]+" - "+b.translateBio),
 d(".readingData",x).html(""),d.get("https://en.wikipedia.org/w/api.php?format=xml&action=query&prop=pageprops|extracts&exintro=&explaintext=&generator=search&gsrsearch="+q[0]+"&gsrlimit=20&origin=*",{},function(c){d("page",c).each(function(){d("pageprops",this).attr("wikibase_item")==a.the_wikidata_id&&(d(".historyTitle_bio",e).html(q[0]+" - "+b.translateBio),d(".readingData",x).html(d("extract ",this).text()))})})),""==v&&d.get("https://www.wikidata.org/w/api.php?action=wbgetclaims&entity="+a.the_wikidata_id+
 "&property=P18&format=xml&origin=*",{},function(c){v=d("datavalue",d("mainsnak",c)).attr("value");V(v,b,a,g)}))});a.no_artist_image_setTimeout=setTimeout(function(){""!=v&&void 0!=v||W(b,a,g,r)},1E3)})},1500))})},1500))}a.curSongText&&(c=a.curSongText.split("-"),a.curSongAuthorText=c[0].trim(),2<=c.length&&(a.curSongText=c[1].trim()),3<=c.length&&(a.curSongAuthorText=c[0].trim()+"-"+c[1].trim(),a.curSongText=c[2].trim()),l.html(aa(a.curSongAuthorText,b)),n.css({width:"auto"}),a.isStationTitleInsideScrolling=
 !1,a.stationTitleInsideWait=0,n.stop(),n.css({"margin-left":0}),n.html(a.curSongText),clearInterval(a.timeupdateInterval),n.width()>a.titleWidth?a.timeupdateInterval=setInterval(function(){!a.isStationTitleInsideScrolling&&5<=a.stationTitleInsideWait&&n.width()>a.titleWidth?(a.isStationTitleInsideScrolling=!0,a.stationTitleInsideWait=0,n.html(a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "),n.css({"margin-left":0}),n.stop().animate({"margin-left":b.playerWidth-
 n.width()+"px"},parseInt(1E4*(n.width()-b.playerWidth)/150,10),"linear",function(){a.isStationTitleInsideScrolling=!1})):!a.isStationTitleInsideScrolling&&n.width()>a.titleWidth&&a.stationTitleInsideWait++},300):n.css({width:"100%"}))}function S(a,b,c,e){if(b.gen_total_images>c.numberOfThumbsPerScreen){var p=(b.thumbsHolder_ThumbHeight+1)*(b.gen_total_images-c.numberOfThumbsPerScreen),l=0;e.stop(!0,!0);d("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){a.preventDefault()});
 -1==a||b.isCarouselScrolling?!b.isCarouselScrolling&&b.gen_total_images>c.numberOfThumbsPerScreen&&(b.isCarouselScrolling=!0,l=-1*parseInt((b.thumbsHolder_ThumbHeight+1)*b.current_img_no,10),Math.abs(l)>p&&(l=-1*p),b.gen_total_images>c.numberOfThumbsPerScreen&&c.showPlaylist&&b.audio9_html5_sliderVertical.slider("value",100+parseInt(100*l/p)),e.animate({top:l+"px"},500,"easeOutCubic",function(){b.isCarouselScrolling=!1;d("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){})})):
 (b.isCarouselScrolling=!0,l=2>=a?-1*p:parseInt(p*(a-100)/100,10),0<l&&(l=0),e.animate({top:l+"px"},1100,"easeOutQuad",function(){b.isCarouselScrolling=!1;d("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){})}))}}function T(a,b,c,e,d,l,y,n,t,w,g,z,x,q,r,A,B,k,v,F,h,u,m,C,D,f,E,I,G){e.width(c.playerWidth);if(c.showOnlyPlayButton||b.isMinified)a="none";A.css({width:c.playerWidth+"px",height:parseInt(c.playerWidth/c.origWidth*c.imageHeight,10)+"px","background-image":"url("+
 c.textureOverImage+")","background-repeat":"repeat"});"none"==a?r.css({width:"0px",height:"0px"}):r.css({width:c.playerWidth+"px",height:parseInt(c.playerWidth/c.origWidth*c.imageHeight,10)+"px"});c.sticky&&c.startMinified?r.css({display:"none",top:"0px",left:"0px"}):r.css({display:a,top:"0px",left:"0px"});b.imageTopPos=0;b.imageLeftPos=0;a="none";if(b.isMinified){if(b.frameBehindTextTopPos=0,b.frameBehindTextLeftPos=0,a=c.frameBehindTextColor,-1!=c.frameBehindTextColor.indexOf(".jpg")||-1!=c.frameBehindTextColor.indexOf(".jpeg")||
 -1!=c.frameBehindTextColor.indexOf(".gif")||-1!=c.frameBehindTextColor.indexOf(".png"))a="url("+c.frameBehindTextColor+")"}else b.frameBehindTextTopPos=r.height()-80,b.frameBehindTextLeftPos=0;c.showOnlyPlayButton?v.css({top:b.frameBehindTextTopPos+"px",left:b.frameBehindTextLeftPos+"px",background:"url("+c.frameBehindTextColor+")",width:0,height:0}):v.css({top:b.frameBehindTextTopPos+"px",left:b.frameBehindTextLeftPos+"px",background:a,height:t.height()+2*b.playVerticalPadding+h.height()+3+"px"});
 b.playTopPos=b.frameBehindTextTopPos+b.playVerticalPadding;b.isMinified&&(b.playTopPos=b.frameBehindTextTopPos+parseInt((v.height()-t.height())/2,10));b.playLeftPos=b.frameBehindTextLeftPos+b.playHorizontalPadding;t.css({top:b.playTopPos+"px",left:b.playLeftPos+"px","background-color":c.buttonsOffState});b.titleWidth=parseInt(.75*c.playerWidth,10);r="center";b.isMinified?(b.titleTopPos=b.playTopPos+3,b.titleLeftPos=t.width()+2*b.playHorizontalPadding,r="left",b.titleWidth=c.playerWidth-4*b.playHorizontalPadding-
 t.width()):c.centerTitle?(b.titleTopPos=parseInt(c.playerWidth/c.origWidth*c.imageHeight*.26,10),b.titleLeftPos=parseInt((c.playerWidth-b.titleWidth)/2,10)):(r="left",b.titleTopPos=b.playTopPos-70,b.titleLeftPos=b.playLeftPos,b.titleWidth=c.playerWidth-2*b.playLeftPos);g.css({color:c.songTitleColor,top:b.titleTopPos+"px",left:b.titleLeftPos+"px",width:b.titleWidth+"px"});z.css({"text-align":r});b.lineSeparatorTopPos=b.titleTopPos+g.height()+2;b.lineSeparatorLeftPos=b.titleLeftPos;F.css({background:c.lineSeparatorColor,
 opacity:c.lineSeparatorOpacity/100,top:b.lineSeparatorTopPos+"px",left:b.lineSeparatorLeftPos+"px",width:b.titleWidth+"px"});b.isMinified?(b.authorTopPos=b.lineSeparatorTopPos+8,b.authorLeftPos=b.titleLeftPos,r="left"):(b.authorTopPos=b.lineSeparatorTopPos+8,b.authorLeftPos=b.titleLeftPos,r=c.centerTitle?"center":"left");w.css({color:c.authorTitleColor,top:b.authorTopPos+"px",left:b.authorLeftPos+"px",width:b.titleWidth+"px","text-align":r});b.minimizeTopPos=10;!c.sticky||c.showOnlyPlayButton?(b.minimizeRightPos=
 0,u.css({display:"none",padding:0,margin:0})):c.sticky&&(b.minimizeRightPos=b.smallButtonDistance,u.css({display:"block",top:b.minimizeTopPos+"px",right:b.minimizeRightPos+"px"}),(b.isBioVisible||b.isHistoryVisible)&&u.css({display:"none"}));b.frameBehindButtonsTopPos=b.isMinified?v.height()-h.height():0;b.frameBehindButtonsLeftPos=0;c.showOnlyPlayButton?h.css({background:"none",height:0,top:b.frameBehindButtonsTopPos+"px",left:b.frameBehindButtonsLeftPos+"px"}):h.css({background:"none",top:b.frameBehindButtonsTopPos+
 "px",left:b.frameBehindButtonsLeftPos+"px"});b.radioStationTopPos=b.isMinified?b.minimizeTopPos-4:b.frameBehindButtonsTopPos+Math.floor(h.height()-x.height())/2;b.radioStationLeftPos=b.playHorizontalPadding;x.css({color:c.radioStationColor,top:b.radioStationTopPos+"px",left:b.radioStationLeftPos+"px",width:b.titleWidth+"px"});0==b.historyButWidth&&(b.historyButWidth=m.width());b.showhidehistoryTopPos=b.isMinified?b.frameBehindButtonsTopPos+Math.floor((h.height()-m.height())/2):parseInt(c.playerWidth/
 c.origWidth*c.imageHeight,10)-12-m.height();b.temp_showHistoryBut?(b.showhideplaylistRightPos=2.5*b.smallButtonDistance,m.css({display:"block",width:b.historyButWidth+"px",top:b.showhidehistoryTopPos+"px",right:b.showhideplaylistRightPos+"px","background-color":c.buttonsOffState})):(b.showhideplaylistRightPos=0,m.css({display:"none",width:0,padding:0,margin:0}));C.css({display:"none",width:0,padding:0,margin:0});b.volumeTopPos=b.isMinified?b.frameBehindButtonsTopPos+Math.floor((h.height()-D.height())/
 2)+3:parseInt(c.playerWidth/c.origWidth*c.imageHeight,10)-12-D.height();c.showVolume?(b.volumeRightPos=b.showhideplaylistRightPos+m.width()+b.smallButtonDistance,D.css({top:b.volumeTopPos+"px",right:b.volumeRightPos+"px","background-color":c.buttonsOffState})):(b.volumeRightPos=b.showhideplaylistRightPos+m.width(),D.css({display:"none",width:0,padding:0,margin:0}));b.twitterTopPos=b.isMinified?b.frameBehindButtonsTopPos+Math.floor((h.height()-f.height())/2)+3:parseInt(c.playerWidth/c.origWidth*c.imageHeight,
 10)-12-f.height();c.showTwitterBut?(b.twitterRightPos=b.volumeRightPos+D.width()+b.smallButtonDistance,f.css({top:b.twitterTopPos+"px",right:b.twitterRightPos+"px","background-color":c.buttonsOffState})):(b.twitterRightPos=b.volumeRightPos+D.width(),f.css({display:"none",width:0,padding:0,margin:0}));b.facebookTopPos=b.isMinified?b.frameBehindButtonsTopPos+Math.floor((h.height()-E.height())/2)+3:parseInt(c.playerWidth/c.origWidth*c.imageHeight,10)-12-E.height();c.showFacebookBut?(b.facebookRightPos=
 b.twitterRightPos+f.width()+b.smallButtonDistance,E.css({top:b.facebookTopPos+"px",right:b.facebookRightPos+"px","background-color":c.buttonsOffState})):(b.facebookRightPos=b.twitterRightPos,E.css({display:"none",width:0,padding:0,margin:0}));b.isMinified?G.css({display:"none"}):b.bioTopPos=parseInt(c.playerWidth/c.origWidth*c.imageHeight,10)-12-G.height();c.showBioBut?(b.bioRightPos=b.facebookRightPos+E.width()+b.smallButtonDistance,G.css({display:"block",top:b.bioTopPos+"px",right:b.bioRightPos+
 "px","background-color":c.buttonsOffState})):(b.bioRightPos=b.facebookRightPos,G.css({display:"none",width:0,padding:0,margin:0}));b.lyricsTopPos=b.isMinified?b.frameBehindButtonsTopPos+Math.floor((h.height()-I.height())/2):parseInt(c.playerWidth/c.origWidth*c.imageHeight,10)-12-I.height();c.showLyricsBut?(b.lyricsRightPos=b.bioRightPos+G.width()+b.smallButtonDistance,I.css({top:b.lyricsTopPos+"px",right:b.lyricsRightPos+"px","background-color":c.buttonsOffState})):(b.lyricsRightPos=b.bioRightPos,
 I.css({display:"none",width:0,padding:0,margin:0}))}function R(a,b,c,e,p,l,y,n,t,w,g,z,x,q,r,A,B){if(!b.showOnlyPlayButton){e.stop(!0,!0);a.isCarouselScrolling=!1;d(".readingData",l).css({display:"none"});n=parseInt(b.playerWidth/b.origWidth*b.historyRecordTitleLimit,10);t=parseInt(b.playerWidth/b.origWidth*b.historyRecordAuthorLimit,10);w=[];a.isHistoryGenerated=!0;e.html("");for(g=a.gen_total_images=0;g<a.playlist_arr.length;g++)a.gen_total_images++,w=a.playlist_arr[g].split("-"),1>w.length?a.gen_total_images--:
 (a.thumbsHolder_Thumb=d('<div class="thumbsHolder_ThumbOFF" rel="'+(a.gen_total_images-1)+'" data-origID="'+g+'"><div class="padding"><div class="img_div" style="background-image:url('+a.playlist_images_arr[g]+");background-color:#000000;border:2px solid "+b.historyRecordThumbBorderColor+';"></div><span class="titlex">'+ba(w[1],n,b)+'</span><span class="authorx">'+ba(w[0],t,b)+"</span></div></div>"),e.append(a.thumbsHolder_Thumb),0==a.thumbsHolder_ThumbHeight&&(a.thumbsHolder_ThumbHeight=a.thumbsHolder_Thumb.height()),
 a.thumbsHolder_Thumb.css({top:(a.thumbsHolder_ThumbHeight+1)*a.gen_total_images+"px",background:b.historyRecordBgColor,"border-bottom-color":b.historyRecordBottomBorderColor,color:b.historyRecordTextColor}),d(".titlex",a.thumbsHolder_Thumb).css({color:b.historyRecordSongColor,"border-bottom-color":b.historyRecordSongBottomBorderColor}),d(".authorx",a.thumbsHolder_Thumb).css({color:b.historyRecordAuthorColor}),a.current_img_no=0);p.height(2*b.historyPadding+(a.thumbsHolder_ThumbHeight+1)*b.numberOfThumbsPerScreen+
 B.height()+b.historyPadding);l.height((a.thumbsHolder_ThumbHeight+1)*b.numberOfThumbsPerScreen);l.css({"margin-top":B.height()+b.historyPadding+"px"});y.css({padding:b.historyPadding+"px"});a.thumbsHolder_Thumbs=d(".thumbsHolder_ThumbOFF",c);a.wrapperHeight=a.audioPlayerHeight;a.gen_total_images>b.numberOfThumbsPerScreen?(b.isPlaylistSliderInitialized&&a.audio9_html5_sliderVertical.slider("destroy"),a.audio9_html5_sliderVertical.slider({orientation:"vertical",range:"min",min:1,max:100,step:1,value:100,
 slide:function(c,d){S(d.value,a,b,e)}}),b.isPlaylistSliderInitialized=!0,a.audio9_html5_sliderVertical.css({display:"none",position:"absolute",height:p.height()-20-3*b.historyPadding-B.height()+"px",left:c.width()-a.audio9_html5_sliderVertical.width()-b.historyPadding+"px",top:2*b.historyPadding+2+B.height()+"px"}),a.isHistoryVisible&&a.audio9_html5_sliderVertical.css({display:"block"}),d(".thumbsHolder_ThumbOFF",c).css({width:c.width()-a.audio9_html5_sliderVertical.width()-2*b.historyPadding-3+"px"})):
 (b.isPlaylistSliderInitialized&&(a.audio9_html5_sliderVertical.slider("destroy"),b.isPlaylistSliderInitialized=!1),d(".thumbsHolder_ThumbOFF",c).css({width:c.width()-2*b.historyPadding+"px"}));l.mousewheel(function(c,d,g,h){c.preventDefault();c=a.audio9_html5_sliderVertical.slider("value");if(1<parseInt(c)&&-1==parseInt(d)||100>parseInt(c)&&1==parseInt(d))c+=3*d,a.audio9_html5_sliderVertical.slider("value",c),S(c,a,b,e)});e.css({top:"0px"});a.is_very_first=!1}}function aa(a,b){b.preserveOriginalUpperLowerCase||
 (a=a.toLowerCase(),a=a.replace(/\b[a-z]/g,function(a){return a.toUpperCase()}),a=a.replace(/&Apos;/gi,"'"),a=a.replace(/&Amp;/gi,"&"),a=a.replace(/'[A-Z]/g,function(a){return a.toLowerCase()}));return a}function ba(a,b,c){a=String(a);var e="";if(a.length>b){a=a.substring(0,b);var d=a.split(" ");a=a.substring(b-2,b-1);""!=a&&(d.pop(),e="...");a=d.join(" ")}a=aa(a,c);return a+e}function ea(){d("audio").each(function(){d(".AudioPlay").removeClass("AudioPause");d(this)[0].pause()})}function ca(){var a=
 -1;if("Microsoft Internet Explorer"==navigator.appName){var b=navigator.userAgent,c=/MSIE ([0-9]{1,}[.0-9]{0,})/;null!=c.exec(b)&&(a=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(b=navigator.userAgent,c=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,null!=c.exec(b)&&(a=parseFloat(RegExp.$1)));return parseInt(a,10)}function fa(a){var b=!1;document.getElementById(a.audioID).canPlayType&&"no"!=document.getElementById(a.audioID).canPlayType("audio/mpeg")&&""!=document.getElementById(a.audioID).canPlayType("audio/mpeg")||
 (b=!0);return b}function U(a){return"#"==a.charAt(0)?a.substring(1,7):a}function ha(a){var b=[];b[0]=parseInt(U(a).substring(0,2),16);b[1]=parseInt(U(a).substring(2,4),16);b[2]=parseInt(U(a).substring(4,6),16);return b}var N=navigator.userAgent.toLowerCase();d.fn.audio9_html5=function(a){a=d.extend({},d.fn.audio9_html5.defaults,a);ca();return this.each(function(){var b=d(this),c=d('<div class="frameBehindText"></div><div class="frameBehindButtons"></div> <div class="ximage"></div> <div class="xtexture"></div> <div class="AudioControls"> <a class="AudioCloseBut" title="Minimize"></a><a class="AudioFacebook" title="Facebook"></a><a class="AudioTwitter" title="Twitter"></a><a class="AudioLyrics" title="Lyrics"></a><a class="AudioBio" title="Show/Hide Bio"></a><a class="AudioPlay" title="Play/Pause"></a><a class="AudioShowHidePlaylist" title="Show/Hide History"></a><a class="VolumeButton" title="Mute/Unmute"></a><div class="VolumeSlider"></div>   </div>   <div class="songTitle"><div class="songTitleInside"></div></div>  <div class="songAuthorLineSeparator"></div>  <div class="songAuthor"></div>  <div class="radioStation"></div>     <div class="thumbsHolderWrapper"><div class="historyPadding">  <div class="historyTitle"></div> <div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div></div>  <div class="slider-vertical"></div>  <div class="thumbsHolderWrapper_bio"> <div class="historyPadding_bio"> <div class="historyTitle_bio"></div> <div class="thumbsHolderVisibleWrapper_bio"> </div></div></div>'),
 e=b.parent(".audio9_html5");e.addClass(a.skin);e.append(c);var p=d(".frameBehindText",e),l=d(".frameBehindButtons",e);d(".AudioControls",e);var y=d(".AudioFacebook",e),n=d(".AudioTwitter",e),t=d(".AudioLyrics",e),w=d(".AudioBio",e),g=d(".AudioPlay",e),z=d(".AudioShowHidePlaylist",e),x=d(".VolumeButton",e),q=d(".VolumeSlider",e),r=d(".AudioCloseBut",e),A=d(".songTitle",e),B=d(".songTitleInside",e),k=d(".songAuthor",e),v=d(".songAuthorLineSeparator",e),F=d(".radioStation",e),h=d(".ximage",e),u=d(".xtexture",
 e),m=d(".historyTitle",e);e.wrap("<div class='the_wrapper'></div>");var C=e.parent(),D=ca();if(-1!=N.indexOf("ipad")||-1!=N.indexOf("iphone")||-1!=N.indexOf("ipod")||-1!=N.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android"))a.autoPlay=!1;!1===a.sticky&&-1==(-1==navigator.userAgent.indexOf("Opera")&&navigator.userAgent.indexOf("OPR"))&&(-1!=navigator.userAgent.indexOf("Chrome")&&-1!=navigator.vendor.indexOf("Google")&&(a.autoPlay=!1),-1!=navigator.userAgent.indexOf("Safari")&&-1!=navigator.vendor.indexOf("Apple")&&
 -1==navigator.platform.indexOf("Win")&&(a.autoPlay=!1));e.css({background:"transparent"});var f={current_img_no:0,origID:0,is_very_first:!0,total_images:0,gen_total_images:0,is_changeSrc:!1,timeupdateInterval:"",totalTime:"",playlist_arr:"",playlist_images_arr:"",isCarouselScrolling:!1,isHistoryGenerated:!1,isHistoryVisible:!1,isStationTitleInsideScrolling:!1,curTitle:"",prevTitle:"",cur_song_image:"",prev_song_image:"",curSongText:"",curSongAuthorText:"",stationTitleInsideWait:0,audioPlayerWidth:0,
 audioPlayerHeight:0,wrapperHeight:0,temp_showHistoryBut:!0,historyButWidth:0,isRadioCo:!1,historyInitialHeight:90,thumbsHolder_Thumb:d('<div class="thumbsHolder_ThumbOFF" rel="0"><div class="padding">test</div></div>'),thumbsHolder_ThumbHeight:0,thumbsHolder_Thumbs:"",constantDistance:0,titleWidth:0,radioStationTopPos:0,radioStationLeftPos:0,titleTopPos:0,titleLeftPos:0,lineSeparatorTopPos:0,lineSeparatorLeftPos:0,authorTopPos:0,authorLeftPos:0,minimizeTopPos:0,minimizeRightPos:0,isMinified:!1,imageTopPos:0,
 imageLeftPos:0,frameBehindButtonsTopPos:0,frameBehindButtonsLeftPos:0,frameBehindTextTopPos:0,frameBehindTextLeftPos:0,playTopPos:0,playLeftPos:0,volumeTopPos:0,volumeRightPos:0,volumesliderTopPos:0,volumesliderLeftPos:0,showhidehistoryTopPos:0,showhideplaylistRightPos:0,smallButtonDistance:4,playVerticalPadding:10,playHorizontalPadding:14,facebookTopPos:0,facebookRightPos:0,twitterTopPos:0,twitterRightPos:0,bioTopPos:0,bioRightPos:0,isBioVisible:!1,lyricsTopPos:0,lyricsRightPos:0,origParentFloat:"",
 origParentPaddingTop:"",origParentPaddingRight:"",origParentPaddingBottom:"",origParentPaddingLeft:"",windowWidth:0,audioID:"",audioObj:"",radioReaderAjaxInterval:"",totalRadioStationsNo:0,ajaxReturnedRadioStationsNo:0,lastfm:"",isFlashNeeded:!0,myFlashObject:"",rndNum:0,prevVolumeVal:1,myregexp:/^(http|https):\/\/(.*):(.*)\/(.*)$/,myregexp_radioco:/^(http|https):\/\/(.*)\/(.*)\/(.*)$/,bio_regexp:/<([a-z]+)([^<]+)*(?:>(.*)<\/\1>|\s+\/>)/,http_or_https:"http",ip:"",port:"",mount_point:"",now_playing_current_k:-1,
 now_playing_found:!1,now_playing_arr_lenght:0,now_playing_arr:["stats?sid=1","7.html","status-json.xsl","status.xsl"],history_current_k:0,history_arr:["played.html"],the_artist_id:"",the_wikidata_id:"",musicbrainz_setTimeout:"",no_artist_image_setTimeout:"",the_artist_id_history_arr:[""],the_wikidata_id_history_arr:[""],musicbrainzHistory_setTimeout_arr:[""],wiki_photo_path:a.noImageAvailable};a.preserveOriginalUpperLowerCase||(B.css({"text-transform":"uppercase"}),k.css({"text-transform":"capitalize"}));
 a.sticky||(a.startMinified=!1);30>a.nowPlayingInterval&&(a.nowPlayingInterval=44);a.showOnlyPlayButton&&(a.startMinified=!1,a.showFacebookBut=!1,a.showVolume=!1,a.showTwitterBut=!1,a.showBioBut=!1,a.showLyricsBut=!1,a.showRadioStation=!1,a.showTitle=!1,a.showHistoryBut=!1,a.playerWidth=g.width()+2*f.playHorizontalPadding,a.historyPadding=0);a.origWidth=a.playerWidth;f.temp_showHistoryBut=a.showHistoryBut;f.now_playing_arr_lenght=Object.keys(f.now_playing_arr).length;f.audioID=b.attr("id");f.isFlashNeeded=
 fa(f);-1!=D&&(f.isFlashNeeded=!0);a.showFacebookBut&&(window.fbAsyncInit=function(){FB.init({appId:a.facebookAppID,version:"v2.11",status:!0,cookie:!0,xfbml:!0})},function(a,b,c){var d=a.getElementsByTagName(b)[0];a.getElementById(c)||(a=a.createElement(b),a.id=c,a.src="//connect.facebook.com/en_US/sdk.js",d.parentNode.insertBefore(a,d))}(document,"script","facebook-jssdk"),y.click(function(){FB.ui({method:"feed",name:a.facebookShareTitle,caption:a.radio_name,description:a.facebookShareDescription,
 link:document.URL,picture:a.facebookShareImage},function(a){})}),y.mouseover(function(){y.css({"background-color":a.buttonsOnState})}),y.mouseout(function(){y.css({"background-color":a.buttonsOffState})}));a.showTwitterBut&&(n.click(function(){window.open("https://twitter.com/intent/tweet?url="+document.URL+"&text="+a.radio_name,"Twitter","status = 1, left = 430, top = 270, height = 550, width = 420, resizable = 0")}),n.mouseover(function(){n.css({"background-color":a.buttonsOnState})}),n.mouseout(function(){n.css({"background-color":a.buttonsOffState})}));
 a.showBioBut&&(w.click(function(){if("none"==E.css("display")){f.isBioVisible=!0;var b="block",c=1,d="0px";0>L.css("margin-top").substring(0,L.css("margin-top").length-2)?(c=1,b="block",d="0px",L.css({display:b}),a.showRadioStation&&F.css({display:"none"}),a.showTitle&&(k.css({display:"none"}),v.css({display:"none"}),A.css({display:"none"})),a.sticky&&r.css({display:"none"})):(f.isBioVisible=!1,c=0,b="none",d=-1*parseInt(a.imageHeight/2,10)+"px",a.showRadioStation&&F.css({display:"block"}),a.showTitle&&
 (k.css({display:"block"}),v.css({display:"block"}),A.css({display:"block"})),a.sticky&&r.css({display:"block"}));L.animate({opacity:c,"margin-top":d},500,"easeOutQuad",function(){L.css({display:b})})}}),w.mouseover(function(){w.css({"background-color":a.buttonsOnState})}),w.mouseout(function(){w.css({"background-color":a.buttonsOffState})}));a.showLyricsBut&&(t.click(function(){alert("lyrics")}),t.mouseover(function(){t.css({"background-color":a.buttonsOnState})}),t.mouseout(function(){t.css({"background-color":a.buttonsOffState})}));
 T("block",f,a,e,J,E,G,I,g,k,A,B,F,b,h,u,C,m,p,v,l,r,z,q,x,n,y,t,w);f.audioPlayerHeight=h.height();a.showOnlyPlayButton&&(f.audioPlayerHeight=g.height()+2*f.playVerticalPadding);e.height(f.audioPlayerHeight);if(a.startMinified||a.showOnlyPlayButton)f.historyInitialHeight=0;f.wrapperHeight=f.audioPlayerHeight;C.css({border:a.playerBorderSize+"px solid "+a.playerBorderColor,width:e.width()+"px",height:f.wrapperHeight+"px",overflow:"hidden"});a.centerPlayer&&C.css({margin:"0 auto"});a.sticky&&a.startMinified&&
 C.css({display:"none"});var E=d(".thumbsHolderWrapper",e),I=d(".historyPadding",e),G=d(".thumbsHolderVisibleWrapper",e),J=d(".thumbsHolder",e);f.audio9_html5_sliderVertical=d(".slider-vertical",e);I.css({padding:a.historyPadding+"px"});G.append('<div class="readingData">'+a.translateReadingData+"</div>");m.width(a.playerWidth-2*a.historyPadding);m.html(a.historyTranslate);m.css({color:a.historyTitleColor});c=ha(a.historyBgColor);E.css({width:e.width()+"px",top:"0px",left:"0px",background:"rgba("+
 c[0]+", "+c[1]+", "+c[2]+", "+a.historyBgColorAlpha+")",opacity:0,"margin-top":-1*parseInt(a.imageHeight/2,10)+"px",display:"none"});G.width(e.width());var L=d(".thumbsHolderWrapper_bio",e);L.css({display:"none"});var K=d(".historyPadding_bio",e),O=d(".thumbsHolderVisibleWrapper_bio",e),H=d(".historyTitle_bio",e);a.showBioBut&&(K.css({padding:a.historyPadding+"px"}),O.append('<div class="readingData">'+a.translateReadingData+"</div>"),H.width(a.playerWidth-2*a.historyPadding),H.html(a.translateBio),
 H.css({color:a.historyTitleColor}),L.css({width:e.width()+"px",top:"0px",left:"0px",background:"rgba("+c[0]+", "+c[1]+", "+c[2]+", "+a.historyBgColorAlpha+")",opacity:1,"margin-top":-1*parseInt(a.imageHeight/2,10)+"px",display:"none"}),O.width(e.width()),O.height(f.playTopPos-2*a.historyPadding-f.playVerticalPadding),d(".readingData",O).css({color:a.bioAndLyricsColor,width:a.playerWidth-2*a.historyPadding+"px",height:O.height()-H.height()-2*a.historyPadding+"px"}));a.sticky&&(C.addClass("audio9_html5_sticky_div"),
 r.click(function(){C.css({display:"block"});var c=500;if(f.isMinified){f.isMinified=!1;r.removeClass("AudioOpenBut");c="block";f.temp_showHistoryBut=a.showHistoryBut;f.audioPlayerHeight=parseInt(a.playerWidth/a.origWidth*a.imageHeight,10);var d=f.audioPlayerHeight}else f.isMinified=!0,r.addClass("AudioOpenBut"),c="none",f.audioPlayerHeight=p.height(),d=f.audioPlayerHeight,f.temp_showHistoryBut=!1;T(c,f,a,e,J,E,G,I,g,k,A,B,F,b,h,u,C,m,p,v,l,r,z,q,x,n,y,t,w);h.css({display:c});a.startMinified?(c=0,
 a.startMinified=!1):c=500;C.animate({height:d},c,"easeOutQuad",function(){})}));q.slider({value:a.initialVolume,step:.05,orientation:"horizontal",range:"min",max:1,animate:!0,slide:function(b,c){a.initialVolume=c.value;f.isFlashNeeded?f.myFlashObject.myAS3function(Q(f,a,J,e),a.initialVolume):document.getElementById(f.audioID).volume=c.value},stop:function(a,b){}});document.getElementById(f.audioID).volume=a.initialVolume;q.css({background:a.volumeOffColor});d(".ui-slider-range",q).css({background:a.volumeOnColor});
 g.click(function(){var b=f.isFlashNeeded?!g.hasClass("AudioPause"):document.getElementById(f.audioID).paused;ea();0==b?(f.isFlashNeeded?f.myFlashObject.myAS3function("_pause_radio_stream_",a.initialVolume):document.getElementById(f.audioID).pause(),g.removeClass("AudioPause")):(f.isFlashNeeded?f.myFlashObject.myAS3function("_play_radio_stream_",a.initialVolume):(document.getElementById(f.audioID).src=Q(f,a,J,e),document.getElementById(f.audioID).load(),document.getElementById(f.audioID).play()),g.addClass("AudioPause"))});
 g.mouseover(function(){g.css({"background-color":a.buttonsOnState})});g.mouseout(function(){g.css({"background-color":a.buttonsOffState})});z.click(function(){if("none"==L.css("display")){var b="block",c=1,d="0px";0>E.css("margin-top").substring(0,E.css("margin-top").length-2)?(f.isHistoryVisible=!0,c=1,b="block",d="0px",E.css({display:b}),a.showRadioStation&&F.css({display:"none"}),a.showTitle&&(k.css({display:"none"}),v.css({display:"none"}),A.css({display:"none"})),a.sticky&&r.css({display:"none"})):
 (f.isHistoryVisible=!1,c=0,b="none",d=-1*parseInt(a.imageHeight/2,10)+"px",f.gen_total_images>a.numberOfThumbsPerScreen&&f.audio9_html5_sliderVertical.css({opacity:c,display:b}),a.showRadioStation&&F.css({display:"block"}),a.showTitle&&(k.css({display:"block"}),v.css({display:"block"}),A.css({display:"block"})),a.sticky&&r.css({display:"block"}));E.animate({opacity:c,"margin-top":d},500,"easeOutQuad",function(){E.css({display:b});f.gen_total_images>a.numberOfThumbsPerScreen&&f.audio9_html5_sliderVertical.css({opacity:c,
 display:b})})}});z.mouseover(function(){z.css({"background-color":a.buttonsOnState})});z.mouseout(function(){z.css({"background-color":a.buttonsOffState})});x.click(function(){document.getElementById(f.audioID).muted?(document.getElementById(f.audioID).muted=!1,x.removeClass("VolumeButtonMuted"),f.isFlashNeeded&&(a.initialVolume=f.prevVolumeVal,f.myFlashObject.myAS3function(Q(f,a,J,e),a.initialVolume))):(document.getElementById(f.audioID).muted=!0,x.addClass("VolumeButtonMuted"),f.isFlashNeeded&&
 (f.prevVolumeVal=a.initialVolume,a.initialVolume=0,f.myFlashObject.myAS3function(Q(f,a,J,e),a.initialVolume)))});x.mouseover(function(){x.css({"background-color":a.buttonsOnState})});x.mouseout(function(){x.css({"background-color":a.buttonsOffState})});J.swipe({swipeStatus:function(b,c,e,g,h,k){"up"!=e&&"down"!=e||0==g||(currentScrollVal=f.audio9_html5_sliderVertical.slider("value"),currentScrollVal="up"==e?currentScrollVal-1.5:currentScrollVal+1.5,f.audio9_html5_sliderVertical.slider("value",currentScrollVal),
 d("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){a.preventDefault()}),S(currentScrollVal,f,a,J))},threshold:100,maxTimeThreshold:500,fingers:"all"});f.isFlashNeeded&&(f.rndNum=parseInt(998999*Math.random()+1E3),e.append("<div id='swfHolder"+f.rndNum+"'></div>"),swfobject.addDomLoadEvent(function(){f.myFlashObject=swfobject.createSWF({data:a.pathToAjaxFiles+"flash_player.swf",width:"0",height:"0"},{flashvars:"streamUrl="+a.radio_stream+"&autoPlay="+a.autoPlay+"&initialVolume="+
 a.initialVolume},"swfHolder"+f.rndNum)}),a.autoPlay&&g.addClass("AudioPause"));da(f,a,J,e,g,k,A,B,F,b,h,u,G,E,I,C,m,r,O);-1==N.indexOf("ipad")&&-1==N.indexOf("iphone")&&-1==N.indexOf("ipod")&&-1==N.indexOf("webos")||g.removeClass("AudioPause");var P=function(){""==f.origParentFloat&&(f.origParentFloat=e.parent().css("float"),f.origParentPaddingTop=e.parent().css("padding-top"),f.origParentPaddingRight=e.parent().css("padding-right"),f.origParentPaddingBottom=e.parent().css("padding-bottom"),f.origParentPaddingLeft=
 e.parent().css("padding-left"));a.playerWidth!=a.origWidth||a.playerWidth>d(window).width()?e.parent().css({"float":"none","padding-top":0,"padding-right":0,"padding-bottom":0,"padding-left":0}):e.parent().css({"float":f.origParentFloat,"padding-top":f.origParentPaddingTop,"padding-right":f.origParentPaddingRight,"padding-bottom":f.origParentPaddingBottom,"padding-left":f.origParentPaddingLeft});var c=e.parent().parent().width();e.width()!=c&&(a.playerWidth=a.origWidth+2*a.playerBorderSize>c?c-2*
 a.playerBorderSize:a.origWidth,e.width()!=a.playerWidth&&(T("block",f,a,e,J,E,G,I,g,k,A,B,F,b,h,u,C,m,p,v,l,r,z,q,x,n,y,t,w),f.audioPlayerHeight=h.height(),f.isMinified&&(f.audioPlayerHeight=p.height()),e.height(f.audioPlayerHeight),f.wrapperHeight=f.audioPlayerHeight,C.css({width:e.width()+"px",height:f.wrapperHeight+"px"}),m.width(a.playerWidth-2*a.historyPadding),E.css({width:e.width()+"px",top:"0px"}),G.width(e.width()),R(f,a,e,J,E,G,I,g,k,A,B,F,b,h,u,C,m),a.showBioBut&&(L.css({width:e.width()+
 "px"}),O.width(e.width()),d(".readingData",O).css({width:a.playerWidth-2*a.historyPadding+"px"}))),a.playerWidth<d(window).width()&&e.parent().css({"float":f.origParentFloat,"padding-top":f.origParentPaddingTop,"padding-right":f.origParentPaddingRight,"padding-bottom":f.origParentPaddingBottom,"padding-left":f.origParentPaddingLeft}))},M=!1;d(window).resize(function(){doResizeNow=!0;-1!=D&&9==D&&0==f.windowWidth&&(doResizeNow=!1);f.windowWidth==d(window).width()?(doResizeNow=!1,a.windowCurOrientation!=
 window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,doResizeNow=!0)):f.windowWidth=d(window).width();a.responsive&&doResizeNow&&(!1!==M&&clearTimeout(M),M=setTimeout(function(){P()},300))});a.responsive&&P()})};d.fn.audio9_html5.defaults={radio_stream:"http://194.232.200.150:80/;",radio_name:"Idobi Anthm",playerWidth:355,imageHeight:355,skin:"blackControllers",initialVolume:1,autoPlay:!0,loop:!0,playerBg:"#000000",volumeOffColor:"#454545",volumeOnColor:"#ffffff",
 timerColor:"#ffffff",buttonsOffState:"#FFFFFF",buttonsOnState:"#00AFEF",songTitleColor:"#ffffff",authorTitleColor:"#ffffff",lineSeparatorColor:"#FFFFFF",lineSeparatorOpacity:50,radioStationColor:"#ffffff",frameBehindTextColor:"#000000",frameBehindButtonsColor:"#454545",playerBorderSize:0,playerBorderColor:"#000000",sticky:!1,startMinified:!1,showOnlyPlayButton:!1,centerPlayer:!1,showFacebookBut:!0,facebookAppID:"",facebookShareTitle:"HTML5 Radio Player With History - Shoutcast and Icecast",facebookShareDescription:"A top-notch responsive HTML5 Radio Player compatible with all major browsers and mobile devices.",
 facebookShareImage:"",showVolume:!0,showTwitterBut:!0,showBioBut:!0,showLyricsBut:!1,showRadioStation:!0,showTitle:!0,showHistoryBut:!0,translateReadingData:"reading history...",historyTranslate:"HISTORY - latest played songs",historyTitleColor:"#008aa4",historyBgColor:"#FFFFFF",historyBgColorAlpha:.9,historyRecordBgColor:"transparent",historyRecordBottomBorderColor:"transparent",historyRecordSongColor:"#000000",historyRecordSongBottomBorderColor:"#008aa4",historyRecordAuthorColor:"#6d6d6d",historyRecordThumbBorderColor:"#000000",
 translateBio:"Bio",translateLyrics:"Lyrics",bioAndLyricsColor:"#000000",numberOfThumbsPerScreen:3,historyPadding:16,preserveOriginalUpperLowerCase:!1,centerTitle:!1,responsive:!0,historyRecordTitleLimit:25,historyRecordAuthorLimit:36,nowPlayingInterval:40,grabLastFmPhoto:!0,pathToAjaxFiles:"",noImageAvailable:"noimageavailable.jpg",textureOverImage:"controllers/texture4x4_1.png",lastFMApiKey:"",lastFMSecret:"",origWidth:0,isSliderInitialized:!1,isProgressInitialized:!1,isPlaylistSliderInitialized:!1}})(jQuery);
